name: Cordova Android (latest)

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  cordova-android-latest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'temurin'
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Build test app
      run: |
        npx cordova create temp
        cd temp
        npx cordova platform add android
        npx cordova plugin add .. --noregistry --force --link
        npx cordova platform prepare android
        npx cordova platform build android
