name: Cordova

on:
  workflow_dispatch:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  cordova-android:
    name: cordova@${{ matrix.cordova }} android@${{ matrix.platform }}
    runs-on: ubuntu-${{ matrix.ubuntu }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - jdk: 17
            cordova: latest
            platform: latest
            node: 18.x
            ubuntu: 22.04
            android-cmdline-tools-version: 10406996
          - jdk: 16
            cordova: 12
            platform: 12
            node: 18.x
            ubuntu: 22.04
            android-cmdline-tools-version: 9862592

    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: ${{ matrix.android-cmdline-tools-version }}
      - name: Build test app
        run: |
          sdkmanager "build-tools;30.0.3"
          sdkmanager "build-tools;34.0.0"
          npm install -g cordova@${{ matrix.cordova }}
          cordova create temp
          cd temp
          cordova platform add android@${{ matrix.platform }}
          cordova plugin add .. --noregistry --force --link
          cordova build android

  cordova-ios:
    name: cordova@${{ matrix.cordova }} ios@${{ matrix.platform }}

    runs-on: macos-latest

    strategy:
      matrix:
        include:
          - cordova: latest
            platform: latest
            node: 18.x

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Build test app
        run: |
          npm install -g cordova@${{ matrix.cordova }}
          cordova create temp
          cd temp
          cordova platform add ios@${{ matrix.platform }}
          cordova plugin add .. --noregistry --force --link
          cordova build ios
